version: "3.8"

services:
  nginx:
    build: ./nginx
    image: custome_nginx
    container_name: "ironman"
    ports: 
     - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - spiderman
  django_app:
    build: .
    image: docker_app
    container_name: "thor"
    ports:
      - "8000:8000"
    command: sh -c "python  manage.py migrate --noinput && gunicorn booking_system.wsgi --bind 0.0.0.0:8000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - spiderman

networks:
  spiderman:
